CREATE DATABASE WMS
GO

USE WMS

CREATE TABLE Clients(
	ClientId INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL
)

CREATE TABLE Mechanics(
	MechanicId INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Address VARCHAR(255) NOT NULL
)

CREATE TABLE Models(
	ModelId INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Vendors(
	VendorId INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts(
	PartId INT NOT NULL PRIMARY KEY IDENTITY,
	SerialNumber VARCHAR(50) UNIQUE NOT NULL,
	Description VARCHAR(255),
	Price MONEY NOT NULL,
	VendorId INT NOT NULL,
	StockQty INT NOT NULL DEFAULT 0,

	CONSTRAINT CHK_Parts_Price CHECK (Price > 0),
	CONSTRAINT FK_Parts_Vendors FOREIGN KEY (VendorId) REFERENCES Vendors(VendorId),
	CONSTRAINT CHK_Parts_Qty CHECK (StockQty >= 0)
)

CREATE TABLE Jobs(
	JobId INT NOT NULL PRIMARY KEY IDENTITY,
	ModelId INT NOT NULL,
	Status VARCHAR(11) NOT NULL DEFAULT 'Pending',
	ClientId INT NOT NULL,
	MechanicId INT,
	IssueDate DATE NOT NULL,
	FinishDate DATE,

	CONSTRAINT FK_Jobs_Models FOREIGN KEY (ModelId) REFERENCES Models(ModelId),
	CONSTRAINT CHK_Jobs_StatusValue CHECK (Status IN('Pending', 'In Progress', 'Finished')),
	CONSTRAINT FK_Jobs_Clients FOREIGN KEY (ClientId) REFERENCES Clients(ClientId),
	CONSTRAINT FK_Jobs_Mechanics FOREIGN KEY (MechanicId) REFERENCES Mechanics(MechanicId)
)

CREATE TABLE Orders(
	OrderId INT NOT NULL PRIMARY KEY IDENTITY,
	JobId INT NOT NULL,
	IssueDate DATE,	
	Delivered BIT DEFAULT 'False' NOT NULL,

	CONSTRAINT FK_Orders_Jobs FOREIGN KEY (JobId) REFERENCES Jobs(JobId)
)

CREATE TABLE OrderParts(
	OrderId INT NOT NULL,
	PartId INT NOT NULL,
	Quantity INT NOT NULL DEFAULT 1,

	CONSTRAINT PK_OrderParts PRIMARY KEY (OrderId, PartId),
	CONSTRAINT FK_OrderParts_Orders FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
	CONSTRAINT FK_OrderParts_Parts FOREIGN KEY (PartId) REFERENCES Parts(PartId),
	CONSTRAINT CHK_OrdersParts_Qty CHECK (Quantity > 0)
)

CREATE TABLE PartsNeeded(
	JobId INT NOT NULL,
	PartId INT NOT NULL,
	Quantity INT NOT NULL DEFAULT 1,

	CONSTRAINT PK_PartsNeeded PRIMARY KEY (JobId, PartId),
	CONSTRAINT FK_PartsNeeded_Jobs FOREIGN KEY (JobId) REFERENCES Jobs(JobId),
	CONSTRAINT FK_PartsNeeded_Parts FOREIGN KEY (PartId) REFERENCES Parts(PartId),
	CONSTRAINT CHK_PartsNeeded_Qty CHECK (Quantity > 0)
)